[package]
name = "findclone"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
clap = { version = "4.5.29", features = ["derive"] }
data-encoding = "2.8.0"
multimap = "0.10.0"
rayon = "1.10.0"
ring = "0.17.8"
walkdir = "2.5.0"

